# https://github.com/sasstools/sass-lint/tree/master/docs/rules

rules:
  class-name-format:
    - 0 # TODO
    - convention: hyphenatedbem
  clean-import-paths: 0
  empty-line-between-blocks: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  no-css-comments: 0
  no-color-literals: 0
  no-empty-rulesets: 0
  no-ids: 0
  property-sort-order: 0
